prometheus:
  enabled: true
  

  ingress:
    enabled: true
    ingressClassName: nginx

    hosts:
      - prometheus.shopnest.com
    
    paths:
      - /
    
    pathType: Prefix

  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        release: monitoring


grafana:
  enabled: true

  adminUser: admin
  adminPassword: admin

  ingress:
    enabled: true
    ingressClassName: nginx

    hosts:
      - grafana.shopnest.com
    
    path: /
    
    pathType: Prefix