# values.yml
prometheus:
  enabled: true
  

  ingress:
    enabled: true
    ingressClassName: nginx

    hosts:
      - prometheus.a1320314044f548ffbec89a1f9b6d56e-920795038.ap-south-1.elb.amazonaws.com
    
    paths:
      - /
    
    pathType: Prefix

  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        release: monitoring


grafana:
  enabled: true

  adminUser: admin
  adminPassword: admin

  ingress:
    enabled: true
    ingressClassName: nginx

    hosts:
      - grafana.a1320314044f548ffbec89a1f9b6d56e-920795038.ap-south-1.elb.amazonaws.com/
    
    path: /
    
    pathType: Prefix