prometheus:
  enabled: true

  ingress:
    enabled: false

  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        release: monitoring

grafana:
  enabled: true

  adminUser: admin
  adminPassword: admin

  ingress:
    enabled: false