prometheus:
  enabled: true

  ingress:
    enabled: false

  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        release: monitoring

    externalUrl: "http://a1320314044f548ffbec89a1f9b6d56e-920795038.ap-south-1.elb.amazonaws.com/prometheus/"
    routePrefix: /prometheus

grafana:
  enabled: true

  adminUser: admin
  adminPassword: admin

  ingress:
    enabled: false

  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana/"
      serve_from_sub_path: true