server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # uncomment the following lines to enable proxying to the backend API
    # uncomment the following lines for docker file
    # location /api/ {
    #     proxy_pass http://backend:5000;
    # }
}