apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    
    spec:
      containers:
        - name: shopnest-backend
          image: vinitparmar03/shopnest_backend:04
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: authentication-secret
            - secretRef:
                name: cloudinary-secret
            - secretRef:
                name: gmail-secret
            - secretRef:
                name: mongodb-secret
            - secretRef:
                name: razorpay-secret
          livenessProbe:
            exec:
              command:
                - node
                - healthcheck.js
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 30
            failureThreshold: 5

